### ISSUE TITLE
iPhone X Issue (CSS bottom: 0)

### ISSUE THREAD

**Issue by phillipmoon** [oracle/cordova-plugin-wkwebview-file-xhr#15]
This plugin works perfectly for all iOS devices apart from the new iPhone X.  We've experienced that our CSS style of `bottom: 0` for something `position: absolute` doesn't sit right on the bottom.  There is a gap between the very bottom of the screen and the element we've positioned.  First we thought this could be to account for the "Home bar indicator", but we realised it's quite a bit more than the height given by the CSS constant of `env(safe-area-inset-bottom)` or `constant(safe-area-inset-bottom)`.

Any information, fixes, or workarounds would be appreciated!  Thanks.

**Comment by gvanmat** [comment]
Might be a known wkwebview issue - https://issues.apache.org/jira/browse/CB-12886

**Comment by jacobweber** [comment]
@phillipmoon Did you find a workaround for this?

**Comment by jacobweber** [comment]
Actually it looks like [this](https://github.com/apache/cordova-plugin-wkwebview-engine/issues/53) is the issue, which was fixed in master [here](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/45).

If you include https://github.com/apache/cordova-plugin-wkwebview-engine#master in your config.xml, instead of letting this plugin include the 1.1.4 release automatically, it should fix the bug. I'm not sure if there's anything else unsafe in the master branch though.
