### ISSUE TITLE
.abort() does not work as expected

### ISSUE THREAD

**Issue by jcleyba** [oracle/cordova-plugin-wkwebview-file-xhr#22]
I'm using this plugin and I want to abort all pending requests if the user logs out of my app. The abort() function does not do it.

Debugging I see that this._context.delegate is always null so there's no `abort` function there to be called. I'd appreciate some help with this.

Thanks.

**Comment by gvanmat** [comment]
@jcleyba The cordova API for invoking native iOS code really doesn't provide a way of canceling a request.  The way the plugin works is it makes a single request to the native layer that returns a single response.  Unlike the native behavior of the XMLHttpRequest, the response payload is delivered in a single unit.  Unfortunately, it's not currently possible to abort an in-flight request.

**Comment by gvanmat** [comment]
@jcleyba I'm closing this one as not feasible to fix.  The abort method wasn't implemented due to the plugin's design in how it marshals data from the javascript context to the native layer and back as a single unit.  There is already a substantial overhead in converting all data into base 64 encoded strings.  The single request/response was purposely chosen over multiple requests for performance considerations.
