### ISSUE TITLE
Getting "The network connection was lost." when uploading image file

### ISSUE THREAD

**Issue by yoldar** [oracle/cordova-plugin-wkwebview-file-xhr#42]
Hi!

I'm getting "The network connection was lost." when uploading file. No matter how file size is(tested on 128kb and 2mb). Here are logs:

`Opera Build[4820:554763] Task <0C57E5BB-7A5F-4D18-8391-3A6043AEF13E>.<14> HTTP load failed (error code: -1005 [1:57])`
`Opera Build[4820:554415] Task <0C57E5BB-7A5F-4D18-8391-3A6043AEF13E>.<14> finished with error - code: -1005`
`Opera Build[4820:554279] {"error":"The network connection was lost.","underlyingErrorCode":-1005,"id":"a50c-0.870c710c88a06"}`

Do I need to fix something on server side? Right now nginx is configured to keepalive 65s.

P.s. Using iOS 12.4.

**Comment by noahcooper** [comment]
I get the same error, and it looks like the problem is the `Content-Length` header.

**Comment by elliottpalermo** [comment]
I opened an issue a few days ago because I noticed that we were having problems using multi-part file upload in AngularJS (missing Content-type and boundary). The issue was due to some missing properties that were preventing Object.toString from identifying FormData properly.

It sounds like what you're describing _could_ be caused by that...

You can try the fix I have here and see if solves your issue.

https://github.com/oracle/cordova-plugin-wkwebview-file-xhr/issues/39

**Comment by noahcooper** [comment]
> I opened an issue a few days ago because I noticed that we were having problems using multi-part file upload in AngularJS (missing Content-type and boundary). The issue was due to some missing properties that were preventing Object.toString from identifying FormData properly.
> 
> It sounds like what you're describing _could_ be caused by that...
> 
> You can try the fix I have here and see if solves your issue.
> 
> #39

I'm not sure if @yoldar is experiencing the same issue as me, but I get "The network connection was lost." even when using raw XHR and not the AngularJS `$http` service. As best I can tell, the issue is that the `Content-Length` header is incorrect.

**Comment by noahcooper** [comment]
I just updated the reference to this plugin in my app from:

```
<plugin name="cordova-plugin-wkwebview-file-xhr" spec="~2.1.1" />
```

to:

```
<plugin name="cordova-plugin-wkwebview-file-xhr" spec="https://github.com/oracle/cordova-plugin-wkwebview-file-xhr.git" />
```

With this change, this issue was resolved for me. It appears that there have been a number of changes made here in Git that are not on npm. (The last version on npm is 2 years old, whereas the most recent changes in this repo are from 3 months ago.)

**Comment by manish2788** [comment]
Please verify with latest version of plugin.

**Comment by meghnakaushik1** [comment]
Hello does anyone has this issue resolved?

I am still seeing this issue on iOS specifically

cordova ios 7.1.1

File transfer plugin 2.0.0

File Transfer Error: The network connection was lost
