### ISSUE TITLE
How can I get jQuery to perform a synchronous, rather than asynchronous, Ajax request?

### ISSUE THREAD

**Issue by khjung29** [oracle/cordova-plugin-wkwebview-file-xhr#71]
jQuery.ajax({
    url: strUrl,
    success: function(html) {
      strReturn = html;
    },
    async:false
  });

async: false not working...

**Comment by manish2788** [comment]
@khjung29 This issue doesn't relate to the plugin. You enquire the same in jQuery forum.

**Comment by codeworrior** [comment]
We encounter the same in one of our Cordova apps.

This IMHO is not a question about how to use the jQuery API. What the author does, is a correct way to send sync requests. However, the success handler is not called synchronously as expected, but asynchronously. As a consequence, any sync jQuery.ajax() does not deliver a result.

AFAIK, jQuery's implementation relies on the `readystatechange` event. Is there anything special (non-standard) with respect to the `readystatechange` event in the cordova-plugin-wkwebview-file-xhr?

**Comment by codeworrior** [comment]
I didn't dive too much into it, but looking at [the polyfill's implementation](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr/blob/master/src/www/ios/xhr-polyfill.js#L1221-L1230), I think its `XMLHttpRequest.prototype.send` method cannot deliver the `readystatechange` events synchronously, because its implementation is promise based (using `getHandler()`).

**Comment by vprabusiva** [comment]
I am also faced same issue. Is there any solution???
